line_length: 200
large_tuple: 3
cyclomatic_complexity: 25
force_cast: warning
force_try: warning

disabled_rules:
  - trailing_whitespace

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40

nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

function_parameter_count:
  warning: 5
  error: 10

file_length:
  warning: 1000
  error: 1500

type_body_length:
  warning: 500
  error: 1000
  
function_body_length:
  warning: 100
  error: 200
